### PR TITLE
Add FAQ block to Fractional CTO page

### PR DESCRIPTION
**Pull request by alex-novak**
@albertvolkman  could you deploy it only on Dev site. Matt want to change text in this block before live.

### CODE REVIEW

**Comment by albertvolkman** [comment]
Ready on dev.

**Comment by Melloboy** [comment]
I added my content @albertvolkman. Thank you @alex-novak for getting that together. Can you deploy my changes to the development server and send me the link so I can view before we push to production? Thank you.

**Comment by albertvolkman** [comment]
Ready!

**Comment by alex-novak** [comment]
Hi @albertvolkman we can move it to Prod

**Pull request merged**
