### PR TITLE
[EST-100] Change main meta image

### PR DESCRIPTION
**Pull request by alex-novak**
https://trello.com/c/tzSyPrpN

### CODE REVIEW

**Comment by albertvolkman** [comment]
Does this need to be a png? 719KB is rather large...

**Comment by alex-novak** [comment]
> Does this need to be a png? 719KB is rather large...

Changed, updated

**Comment by albertvolkman** [comment]
Better, but still quite large. Please use this tool to reduce the filesize-

https://compressor.io/

**Comment by alex-novak** [comment]
> Better, but still quite large. Please use this tool to reduce the filesize-
> 
> https://compressor.io/

done

**Comment by albertvolkman** [comment]
Cool. Now could you squash those 3 commits together? 👍

**Comment by alex-novak** [comment]
> Cool. Now could you squash those 3 commits together?

done

**Pull request merged**
